# Generated by Django 6.0 on 2025-12-16 17:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('brand', models.CharField(max_length=100, verbose_name='Марка')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000)], verbose_name='Год выпуска')),
                ('engine_volume', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Объем двигателя (л)')),
                ('fuel_type', models.CharField(choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('hybrid', 'Гибрид'), ('electric', 'Электро')], max_length=20, verbose_name='Тип топлива')),
                ('transmission', models.CharField(choices=[('manual', 'Механика'), ('automatic', 'Автомат'), ('cvt', 'Вариатор'), ('robot', 'Робот')], max_length=20, verbose_name='Коробка передач')),
                ('power', models.PositiveIntegerField(verbose_name='Мощность (л.с.)')),
                ('mileage', models.PositiveIntegerField(default=0, verbose_name='Пробег (км)')),
                ('price_china', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена в Китае ($)')),
                ('price_belarus', models.DecimalField(decimal_places=2, help_text='Ориентировочная цена с учетом растаможки и доставки', max_digits=10, verbose_name='Цена в Беларуси ($)')),
                ('description', models.TextField(verbose_name='Описание')),
                ('features', models.TextField(help_text='Укажите через запятую', verbose_name='Особенности')),
                ('main_image', models.ImageField(upload_to='cars/main/', verbose_name='Главное фото')),
                ('image_1', models.ImageField(blank=True, upload_to='cars/additional/', verbose_name='Фото 2')),
                ('image_2', models.ImageField(blank=True, upload_to='cars/additional/', verbose_name='Фото 3')),
                ('is_available', models.BooleanField(default=True, verbose_name='В наличии')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'ordering': ['-created_at'],
            },
        ),
    ]
