# Generated by Django 6.0 on 2025-12-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='features',
        ),
        migrations.RemoveField(
            model_name='car',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='car',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='car',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='car',
            name='mileage',
        ),
        migrations.RemoveField(
            model_name='car',
            name='power',
        ),
        migrations.RemoveField(
            model_name='car',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='car',
            name='title',
        ),
        migrations.RemoveField(
            model_name='car',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='car',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, default='Прямая поставка из Китая. Отличное состояние.', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_volume',
            field=models.DecimalField(decimal_places=1, default=1.6, max_digits=3, verbose_name='Объем двигателя (л)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('hybrid', 'Гибрид')], default='petrol', max_length=20, verbose_name='Тип топлива'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price_belarus',
            field=models.DecimalField(decimal_places=2, default=32000, max_digits=10, verbose_name='Цена в Беларуси ($)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price_china',
            field=models.DecimalField(decimal_places=2, default=25000, max_digits=10, verbose_name='Цена в Китае ($)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('manual', 'Механика'), ('automatic', 'Автомат')], default='automatic', max_length=20, verbose_name='Коробка передач'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(verbose_name='Год выпуска'),
        ),
    ]
