# Generated by Django 6.0 on 2025-12-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_car_features_remove_car_image_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='features',
            field=models.TextField(blank=True, default='Климат-контроль, камера заднего вида, парктроник', verbose_name='Особенности'),
        ),
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Фотография'),
        ),
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(default=0, verbose_name='Пробег (км)'),
        ),
        migrations.AddField(
            model_name='car',
            name='power',
            field=models.IntegerField(default=150, verbose_name='Мощность (л.с.)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('hybrid', 'Гибрид'), ('electric', 'Электро')], default='petrol', max_length=20, verbose_name='Тип топлива'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('manual', 'Механика'), ('automatic', 'Автомат'), ('cvt', 'Вариатор')], default='automatic', max_length=20, verbose_name='Коробка передач'),
        ),
    ]
